Feature/batterystate
ToyotaResearchInstitute/task_behavior_ros pull request #1
Opened 2017-02-15 20:04 UTC by athackst

2017-02-15 23:06 UTC, LauraStelzner-TRI requested changes

2017-02-15 23:06 UTC, LauraStelzner-TRI commented on src/task_behavior_ros/batterystate.py
> +    Checks if msg indicates charge is ok.
What does ok mean in this case?  Does it mean currently charging with no failures? Does it mean the charge level is above some threshold? Please clarify

2017-02-15 23:06 UTC, LauraStelzner-TRI commented on src/task_behavior_ros/topic.py
> +        self.latch = latch
Please add a comment defining latch functionality

2017-02-15 23:06 UTC, LauraStelzner-TRI commented on test/test_batterystate.py
> +
Please add cases for power_supply_status_unknown, not_charging, and full

2017-02-15 23:06 UTC, LauraStelzner-TRI commented on test/test_batterystate.py
> +
extra newline

2017-02-15 23:06 UTC, LauraStelzner-TRI commented on test/test_batterystate.py
> +
extra newline

2017-02-17 19:05 UTC, athackst commented
@LauraStelzner-TRI @brandonnorthcutt-tri -- Updated unit tests, please take another look.

2017-02-20 08:22 UTC, closed without merging