Feature/battery
ToyotaResearchInstitute/task_behavior_ros pull request #3
Opened 2017-02-21 23:43 UTC by athackst

2017-02-22 00:26 UTC, tinawright requested changes
nice tests!

2017-02-22 00:26 UTC, tinawright commented on src/task_behavior_ros/batterystate.py
> +
nit: extra newline

2017-02-22 00:26 UTC, tinawright commented on src/task_behavior_ros/batterystate.py
> +    @param name [topic_name] The name of the topic
i think this should be 
@param topic_name [str] ...

2017-02-22 00:26 UTC, tinawright commented on src/task_behavior_ros/batterystate.py
> +            cb=self.charge_complete_cb, queue_size=1, *args, **kwargs)
you have queue_size default set twice, here and on the args to this method. I think once is enough.

2017-02-22 00:26 UTC, tinawright commented on src/task_behavior_ros/batterystate.py
> +        super(ChargeCompleteMonitor, self).__init__(
not sure what version of python, but if 3+ can just do "super().__init__("

2017-02-22 00:26 UTC, tinawright commented on src/task_behavior_ros/batterystate.py
> +    @param name [topic_name] The name of the topic
same param question

2017-02-22 00:26 UTC, tinawright commented on src/task_behavior_ros/batterystate.py
> +            cb=self.charge_ok_cb, queue_size=1, *args, **kwargs)
same default arg question

2017-02-22 00:26 UTC, tinawright commented on src/task_behavior_ros/batterystate.py
> +        @param max_charge [float] Number between (0., 1.) that indicates charging percentage
nit: newline after this line instead of before since it's part of @params?

2017-02-22 00:26 UTC, tinawright commented on src/task_behavior_ros/batterystate.py
> +        if msg.percentage > nodedata.get_data('min_charge', 1.):
so the default min charge is 1? seems high.

2017-02-22 00:26 UTC, tinawright commented on test/test_batterystate.py
> +        assert_equal(result.status, NodeStatus.SUCCESS)
this test is funny to me, when would be see a full status with a low percentage?

2017-02-22 00:26 UTC, tinawright commented on test/test_batterystate.py
> +        assert_equal(result.status, NodeStatus.FAIL)
I worry a bit about declaring unknown values as success or fail. perhaps add a line to the class doc specifying this behavior so callers can plan accordingly?

2017-02-22 00:26 UTC, tinawright commented on test/test_batterystate.py
> +        assert_equal(result.status, NodeStatus.FAIL)
why is discharging at max a fail? also percentage 0 is max?

2017-02-22 00:26 UTC, tinawright commented on src/task_behavior_ros/batterystate.py
> +    Checks if msg indicates charge is ok.
I think perhaps I don't understand exactly what you mean by this. in the tests if the charge is full this returns FAIL. I would expect full charge to return success.

2017-02-22 18:10 UTC, LauraStelzner-TRI reviewed
Have some questions to clarify my understanding.  See below.

2017-02-22 18:10 UTC, LauraStelzner-TRI commented on src/task_behavior_ros/batterystate.py
> +            if msg.percentage > nodedata.get_data('max_charge', 1.):
Should this be >= ? Or with how a battery is charged and reported do we actually want it to get greater than 1.0(assuming that is the specified max)?

2017-02-22 18:10 UTC, LauraStelzner-TRI commented on test/test_batterystate.py
> +        assert_equal(result.status, NodeStatus.FAIL)
I also don't understand why this case is a fail.

2017-02-22 18:10 UTC, LauraStelzner-TRI commented on test/test_batterystate.py
> +        msg.percentage = 0.
Confused by the comment 'at max', is that referring to min_charge  or to percentage? Why is percentage a 0? Shouldn't it be 1. if its max?

2017-02-22 18:10 UTC, LauraStelzner-TRI commented on test/test_batterystate.py
> +        assert_equal(result.status, NodeStatus.FAIL)
Is the failing for this case because percentage is 0 and the status is full?

2017-02-22 18:10 UTC, LauraStelzner-TRI commented on test/test_batterystate.py
> +                '--xunit-file='+str(args.gtest_output.lstrip('xml:'))]
Is the xunit required for Jenkins integration?

2017-02-22 18:10 UTC, LauraStelzner-TRI commented on test/test_topic.py
> +    def test_latch_cb(self):
Is there a case for testing the value of what is latched?

2017-02-22 18:10 UTC, LauraStelzner-TRI commented on test/test_topic.py
> +        rospy.sleep(0.2)
Why .2 instead of .1?

2017-02-22 21:50 UTC, athackst commented on src/task_behavior_ros/batterystate.py
> +
My auto-formatter did this, so I think it's a PEP-8 thing

https://www.python.org/dev/peps/pep-0257/#multi-line-docstrings ?

2017-02-22 21:50 UTC, athackst commented on src/task_behavior_ros/batterystate.py
> +    @param name [topic_name] The name of the topic
right you are

2017-02-22 21:50 UTC, athackst commented on src/task_behavior_ros/batterystate.py
> +        @param max_charge [float] Number between (0., 1.) that indicates charging percentage
I wanted to separate it out, since you assign it differently.  But +1 to new line after.

2017-02-22 21:50 UTC, athackst commented on src/task_behavior_ros/batterystate.py
> +        super(ChargeCompleteMonitor, self).__init__(
yeah.. indigo is stuck with 2.7

2017-02-22 21:50 UTC, athackst commented on src/task_behavior_ros/batterystate.py
> +            cb=self.charge_complete_cb, queue_size=1, *args, **kwargs)
woops,  I think that this makes what you set for queue_size not pass through.  updated

2017-02-22 21:50 UTC, athackst commented on src/task_behavior_ros/batterystate.py
> +    Checks if msg indicates charge is ok.
What if the charge "state" is "FULL" but the charge percentage is super low?  Ignore or go back to base?  I err'd on the side of "say things are wrong" -> ChargeOK = FAIL

2017-02-22 21:50 UTC, athackst commented on src/task_behavior_ros/batterystate.py
> +    @param name [topic_name] The name of the topic
yep, fixed.

2017-02-22 21:50 UTC, athackst commented on src/task_behavior_ros/batterystate.py
> +            cb=self.charge_ok_cb, queue_size=1, *args, **kwargs)
yep, removed

2017-02-22 21:50 UTC, athackst commented on src/task_behavior_ros/batterystate.py
> +        if msg.percentage > nodedata.get_data('min_charge', 1.):
By default, should we say what a "good" minimal charge is?  Can we know?  I err'd on the side of, if not set, basically always say it's not ok.

We could default to always say it's ok, but then you might not realize you didn't set it and run out of battery.

2017-02-22 21:50 UTC, athackst commented on test/test_batterystate.py
> +        assert_equal(result.status, NodeStatus.SUCCESS)
When a battery state message is being stupid?

I tend to treat unit tests as edge cases.  It doesn't matter if it would never happen, but we should do the Right Thing if it does.

So, to me this was "if the battery isn't reporting a good charge level, but is reporting that the battery is full, should we disconnect from the charger?  -> yes (maybe it's "full" because of temperature/voltage reasons? maybe percentage is all messed up?)

2017-02-22 21:50 UTC, athackst commented on test/test_batterystate.py
> +        assert_equal(result.status, NodeStatus.FAIL)
This comment may not be in the right place?

The test is if the power supply is charging and the percentage is below min, FAIL

2017-02-22 21:50 UTC, athackst commented on test/test_batterystate.py
> +        assert_equal(result.status, NodeStatus.FAIL)
I think this comment may be in the wrong place?

If you don't fill in the power_supply_status it defaults to "unknown", in that case I would think you would need to rely only on charging percentage.

2017-02-22 21:50 UTC, athackst commented on test/test_batterystate.py
> +                '--xunit-file='+str(args.gtest_output.lstrip('xml:'))]
Yep, it's to create the appropriately formatted output file for Jenkins

2017-02-22 23:53 UTC, tinawright approved these changes

2017-02-22 23:53 UTC, tinawright commented on test/test_batterystate.py
> +        # Charge at full, report FAIL.
tina confused

2017-02-23 00:54 UTC, athackst reviewed
Changed the behavior so that max_charge and min_charge must be set or they report FAIL.

2017-02-23 00:54 UTC, athackst commented on src/task_behavior_ros/batterystate.py
> +            if msg.percentage > nodedata.get_data('max_charge', 1.):
Either is probably valid, but probably should be explicitly stated.  I think you're probably right in that >= makes more semantic sense.

2017-02-23 00:54 UTC, athackst commented on test/test_batterystate.py
> +        assert_equal(result.status, NodeStatus.FAIL)
I think something funky is going on with git review.  I'm seeing this on line 178 which is in the charging area

2017-02-23 00:54 UTC, athackst commented on test/test_batterystate.py
> +        msg.percentage = 0.
rgr, percentage wrong

2017-02-23 00:54 UTC, athackst commented on test/test_topic.py
> +    def test_latch_cb(self):
Ah, that would be a good test.  Adding.

2017-02-23 01:09 UTC, LauraStelzner-TRI approved these changes
LGTM

2017-02-23 01:51 UTC, merged